name: Deploy to Azure Container Registry

on:
  push:
    branches: [ main, master, AzureAI ]
  pull_request:
    branches: [ main, master ]

env:
  AZURE_WEBAPP_NAME: 'your-webapp-name'
  ACR_NAME: 'your-acr-name'
  RESOURCE_GROUP: 'your-resource-group'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: 'Build and push Docker image'
      run: |
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/nott3chat-backend:${{ github.sha }} ./backend
        docker push ${{ env.ACR_NAME }}.azurecr.io/nott3chat-backend:${{ github.sha }}
        
        # Also tag as latest
        docker tag ${{ env.ACR_NAME }}.azurecr.io/nott3chat-backend:${{ github.sha }} ${{ env.ACR_NAME }}.azurecr.io/nott3chat-backend:latest
        docker push ${{ env.ACR_NAME }}.azurecr.io/nott3chat-backend:latest

    - name: 'Deploy to Azure Web App for Containers'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: ${{ env.ACR_NAME }}.azurecr.io/nott3chat-backend:${{ github.sha }}

    - name: 'Azure logout'
      run: |
        az logout
